document.addEventListener("DOMContentLoaded", () => {
    const greetingElement = document.getElementById("greeting");
    const suggestionElement = document.getElementById("suggestion");
    const suggestBtn = document.getElementById("suggestBtn");
    const darkModeToggle = document.getElementById("darkModeToggle");
    const loadingSpinner = document.getElementById("loadingSpinner");
    const body = document.body;

const activities = [
    // Hoạt động trên YouTube
    "Xem vlog YouTube thư giãn",
    "Xem anime ngắn YouTube",
    "Xem video du lịch YouTube",
    "Xem phim ngắn trên YouTube",
    "Xem video cafe YouTube",
    "Xem AMV anime YouTube",
    "Xem opening anime YouTube",
    "Xem ASMR trên YouTube",
    "Xem ASMR nấu ăn",
    "Xem ASMR vẽ tranh",
    "Xem video piano YouTube",
    "Xem video bento YouTube",
    "Xem video gốm sứ YouTube",
    "Xem video làm bánh YouTube",
    "Xem video làm nến YouTube",
    "Xem video làm xà phòng YouTube",
    "Xem video làm son YouTube",
    "Xem video làm vòng tay YouTube",
    "Xem video làm đồ da YouTube",
    "Xem ASMR Nhật YouTube",
    "Xem ASMR origami YouTube",
    "Xem ASMR trà đạo",
    "Xem ASMR đọc sách YouTube",
    "Xem ASMR dọn phòng YouTube",
    "Xem ASMR làm đồ thủ công",
    "Xem ASMR làm bánh YouTube",
    "Xem ASMR chăm cây YouTube",
    "Xem ASMR đan len YouTube",
    "Xem ASMR làm nến YouTube",
    "Xem ASMR làm đồ gỗ YouTube",
    "Xem video hài ngắn trên YouTube",
    "Xem video lồng tiếng anime",
    "Xem video review anime trên YouTube",
    "Xem video top anime hay trên YouTube",
    "Xem video hướng dẫn vẽ chibi trên YouTube",
    "Xem video nấu món Nhật đơn giản trên YouTube",
    "Xem video hướng dẫn làm sushi trên YouTube",
    "Xem video nghệ thuật thư pháp Nhật trên YouTube",
    "Xem video hướng dẫn làm bánh mochi trên YouTube",
    "Xem video tour đền chùa Nhật trên YouTube",
    "Xem video hướng dẫn làm đồ thủ công Nhật trên YouTube",
    "Xem video nhạc cụ truyền thống Nhật trên YouTube",
    "Xem video lễ hội Nhật Bản trên YouTube",
    "Xem video hướng dẫn mặc kimono trên YouTube",
    "Xem video làm bánh wagashi trên YouTube",
    "Xem video hướng dẫn gấp giấy origami trên YouTube",
    "Xem video về văn hóa trà đạo Nhật trên YouTube",
    "Xem video hướng dẫn vẽ manga trên YouTube",
    "Xem video về phố cổ Nhật Bản trên YouTube",

    // Hoạt động trên Spotify
    "Nghe lo-fi trên Spotify",
    "Nghe podcast trên Spotify",
    "Nghe J-pop trên Spotify",
    "Nghe acoustic trên Spotify",
    "Nghe K-pop trên Spotify",
    "Nghe nhạc anime Spotify",
    "Nghe OST anime Spotify",
    "Nghe nhạc enka Spotify",
    "Nghe nhạc lo-fi Nhật",
    "Nghe nhạc shamisen Spotify",
    "Nghe nhạc classical Spotify",
    "Nghe nhạc jazz nhẹ Spotify",
    "Nghe nhạc piano Spotify",
    "Nghe nhạc folk Spotify",
    "Nghe nhạc bossa nova Spotify",
    "Nghe nhạc ambient Spotify",
    "Nghe nhạc vocaloid trên Spotify",
    "Nghe nhạc cover J-pop trên Spotify",
    "Nghe playlist anime lo-fi trên Spotify",
    "Nghe playlist nhạc chill Nhật trên Spotify",
    "Nghe nhạc truyền thống Nhật trên Spotify",
    "Nghe playlist thư giãn đêm khuya trên Spotify",
    "Nghe playlist lo-fi học bài trên Spotify",
    "Nghe playlist nhạc phim Ghibli trên Spotify",
    "Nghe playlist nhạc game Nhật trên Spotify",
    "Nghe playlist acoustic nhẹ nhàng trên Spotify",
    "Nghe playlist nhạc lo-fi mùa thu trên Spotify",
    "Nghe playlist nhạc Nhật thập niên 90 trên Spotify",
    "Nghe playlist nhạc piano anime trên Spotify",
    "Nghe playlist nhạc lo-fi mùa đông trên Spotify",

    // Hoạt động trên Facebook
    "Lướt ảnh aesthetic Facebook",
    "Lướt meme hài Facebook",
    "Lướt ảnh nghệ thuật Facebook",
    "Lướt bài viết Facebook chill",
    "Lướt ảnh thiên nhiên Facebook",
    "Lướt fanpage anime Facebook",
    "Lướt ảnh cosplay Facebook",
    "Lướt bài cosplay Facebook",
    "Lướt nhóm anime Facebook",
    "Lướt bài Nhật Facebook",
    "Lướt ảnh kawaii Facebook",
    "Lướt fanpage Nhật Facebook",
    "Lướt bài manga Facebook",
    "Lướt ảnh meme anime trên Facebook",
    "Lướt fanpage Studio Ghibli trên Facebook",
    "Lướt bài viết về J-pop trên Facebook",
    "Lướt fanpage cosplay Nhật trên Facebook",
    "Lướt nhóm fan nghệ thuật Nhật trên Facebook",
    "Lướt ảnh festival Nhật trên Facebook",
    "Lướt bài về văn hóa Nhật trên Facebook",
    "Lướt ảnh món ăn Nhật trên Facebook",
    "Lướt nhóm fan manga trên Facebook",
    "Lướt ảnh kimono đẹp trên Facebook",
    "Lướt bài về lễ hội Nhật trên Facebook",
    "Lướt ảnh cảnh đêm Nhật trên Facebook",
    "Lướt nhóm fan J-pop trên Facebook",
    "Lướt ảnh nghệ thuật ukiyo-e trên Facebook",
    "Lướt bài về anime mới trên Facebook",
    "Lướt ảnh nhân vật anime trên Facebook",
    "Lướt nhóm cosplay anime trên Facebook",

    // Hoạt động trên Discord
    "Xem stream Discord chill",
    "Chat Discord thư giãn",
    "Xem video Discord thư giãn",
    "Chat voice Discord chill",
    "Nghe stream Discord nhẹ",
    "Sắp xếp kênh Discord",
    "Sắp xếp vai trò Discord",
    "Tham gia quiz anime trên Discord",
    "Xem stream chơi game trên Discord",
    "Tham gia sự kiện voice chat trên Discord",
    "Tham gia phòng chat anime trên Discord",
    "Tổ chức watch party anime trên Discord",
    "Tham gia thảo luận manga trên Discord",
    "Chia sẻ fanart trên Discord",
    "Tham gia game night trên Discord",
    "Nghe nhạc chung trên Discord",
    "Tham gia phòng học nhóm trên Discord",
    "Chia sẻ meme anime trên Discord",
    "Tham gia sự kiện cosplay trên Discord",
    "Tạo bot Discord đơn giản",

    // Hoạt động trên Google
    "Ngắm fanart trên Google",
    "Tìm hình nền Google",
    "Tìm ảnh anime trên Google",
    "Tìm tranh ukiyo-e Google",
    "Tìm ảnh kimono Google",
    "Tìm ảnh samurai Google",
    "Tìm ảnh onsen Google",
    "Tìm ảnh chùa Nhật",
    "Tìm ảnh manga Google",
    "Tìm ảnh cosplay đẹp trên Google",
    "Tìm ảnh nhân vật anime yêu thích trên Google",
    "Tìm ảnh cảnh anime mùa đông trên Google",
    "Tìm ảnh biểu tượng anime trên Google",
    "Tìm ảnh cảnh biển Google",
    "Tìm ảnh hoàng hôn Google",
    "Tìm ảnh núi Google",
    "Tìm ảnh cây xanh Google",
    "Tìm ảnh hồ nước Google",
    "Tìm ảnh cầu vồng Google",
    "Tìm ảnh cánh đồng Google",
    "Tìm mẹo học Google",
    "Tìm quote hay Google",
    "Tìm ảnh nghệ thuật Nhật trên Google",
    "Tìm ảnh lễ hội Nhật trên Google",
    "Tìm ảnh món ăn Nhật trên Google",
    "Tìm ảnh phố cổ Nhật trên Google",
    "Tìm ảnh vườn Nhật trên Google",
    "Tìm ảnh đèn lồng Nhật trên Google",
    "Tìm ảnh hoa anh đào trên Google",
    "Tìm ảnh núi Phú Sĩ trên Google",

    // Hoạt động trên app vẽ
    "Vẽ tranh trên app",
    "Vẽ doodle trên app",
    "Vẽ phong cảnh trên app",
    "Vẽ nhân vật anime",
    "Vẽ cảnh anime app",
    "Vẽ tranh phong cách Nhật",
    "Vẽ chibi trên app",
    "Vẽ cảnh sakura app",
    "Vẽ nhân vật chibi",
    "Vẽ biểu tượng cảm xúc trên app",
    "Vẽ hoa đơn giản trên app",
    "Vẽ cây cối trên app",
    "Vẽ tranh trừu tượng app",
    "Vẽ động vật trên app",
    "Vẽ cảnh hoàng hôn app",
    "Vẽ biểu tượng anime app",
    "Vẽ tranh mùa thu app",
    "Vẽ sticker trên app",
    "Vẽ tranh hoạt hình app",
    "Vẽ sticker anime trên app",
    "Vẽ nhân vật manga trên app",
    "Vẽ cảnh đêm trên app",
    "Vẽ tranh lo-fi trên app",
    "Vẽ cảnh mùa đông trên app",
    "Vẽ nhân vật game trên app",
    "Vẽ cảnh anime mùa hè trên app",
    "Vẽ tranh pastel trên app",
    "Vẽ biểu tượng kawaii trên app",
    "Vẽ cảnh anime mùa xuân trên app",
    "Vẽ tranh watercolor trên app",

    // Hoạt động trên Steam
    "Chơi game Steam đẹp mắt",
    "Chơi game Steam phong cảnh",
    "Chơi game Steam màu pastel",
    "Chơi game Steam nhẹ",
    "Chơi game anime Steam",
    "Chơi game Nhật Steam",
    "Chơi game visual novel",
    "Chơi game RPG Steam",
    "Chơi game indie Steam",
    "Chơi game pixel Steam",
    "Chơi game otome Steam",
    "Chơi game puzzle Steam",
    "Chơi game mô phỏng Steam",
    "Chơi game nông trại Steam",
    "Chơi game phiêu lưu nhẹ Steam",
    "Chơi game khám phá Steam",
    "Chơi game giải đố Steam",
    "Chơi game nghệ thuật Steam",
    "Chơi game anime miễn phí trên Steam",
    "Chơi game rhythm trên Steam",
    "Chơi game gacha trên Steam",
    "Chơi game thư giãn trên Steam",
    "Chơi game visual novel Nhật trên Steam",
    "Chơi game phiêu lưu anime trên Steam",
    "Chơi game chiến thuật nhẹ trên Steam",
    "Chơi game mô phỏng Nhật trên Steam",
    "Chơi game nghệ thuật pixel trên Steam",
    "Chơi game khám phá văn hóa Nhật trên Steam",
    "Chơi game thư giãn mùa đông trên Steam",
    "Chơi game anime phong cách chibi trên Steam",

    // Hoạt động nấu ăn và đồ uống
    "Pha cà phê hòa tan",
    "Nấu mì gói thơm",
    "Nhâm nhi bim bim",
    "Pha trà xanh túi lọc",
    "Nấu cháo gói nhanh",
    "Pha cà phê sữa đá",
    "Nấu súp gói thơm",
    "Pha trà đào lon",
    "Nấu mì trộn cay",
    "Pha sữa Milo nóng",
    "Pha trà chanh tươi",
    "Nấu phở gói nhanh",
    "Pha cà phê đen đá",
    "Ăn mì gói cay",
    "Gặm bánh Pocky socola",
    "Làm sandwich đơn giản",
    "Uống trà sữa lon",
    "Ăn bánh quy",
    "Nhâm nhi kẹo dẻo",
    "Làm sữa chua trộn",
    "Ăn mì trộn trứng",
    "Nhâm nhi hạt dưa",
    "Gặm bánh mì pate",
    "Uống nước ngọt có ga",
    "Nhâm nhi kẹo bạc hà",
    "Làm trứng chiên nhanh",
    "Uống cà phê lon",
    "Nhâm nhi socola đen",
    "Làm bánh mì bơ",
    "Uống trà chanh lon",
    "Pha trà matcha túi",
    "Làm onigiri đơn giản",
    "Ăn bánh mochi",
    "Nhâm nhi kẹo matcha",
    "Pha trà sen túi",
    "Làm cơm nắm nhanh",
    "Ăn kẹo dẻo ume",
    "Nhâm nhi rong biển sấy",
    "Pha cà phê túi lọc",
    "Ăn bánh dorayaki",
    "Pha trà ô long",
    "Ăn mứt trái cây",
    "Pha trà gừng tươi",
    "Ăn đậu phộng rang",
    "Pha trà bạc hà",
    "Ăn bánh gạo nướng",
    "Pha trà hoa cúc túi lọc",
    "Làm bánh mì kẹp mứt",
    "Ăn bánh quy bơ",
    "Nhâm nhi hạt điều rang",
    "Pha trà táo túi lọc",
    "Ăn bánh waffle nhỏ",
    "Pha trà cam túi lọc",
    "Ăn bánh mì trứng",
    "Pha cà phê latte túi",
    "Ăn bánh bao nhỏ",
    "Pha trà việt quất túi",
    "Ăn bánh crepe đơn giản",
    "Pha trà dâu túi lọc",
    "Ăn bánh donut mini",
    "Pha trà vải túi lọc",
    "Ăn bánh su kem",
    "Pha trà thảo mộc",
    "Ăn bánh trứng nhỏ",
    "Làm takoyaki đơn giản",
    "Ăn bánh taiyaki",
    "Pha trà hoa hồng túi lọc",
    "Ăn bánh dango",
    "Làm bánh mì kẹp cá ngừ",
    "Ăn bánh mì nướng mứt",
    "Pha trà quế túi lọc",
    "Ăn bánh mì kẹp bơ đậu phộng",
    "Làm bánh mì kẹp rau củ",
    "Ăn bánh mì nướng phô mai",
    "Pha trà chanh dây túi lọc",
    "Ăn bánh mì kẹp trứng luộc",
    "Làm bánh mì nướng mật ong",
    "Ăn bánh mì kẹp thịt nguội",
    "Pha trà xoài túi lọc",
    "Ăn bánh mì kẹp mứt dâu",
    "Làm bánh mì nướng bơ tỏi",
    "Ăn bánh mì kẹp xúc xích",
    "Pha trà dứa túi lọc",
    "Ăn bánh mì kẹp phô mai tan chảy",

    // Hoạt động nghe âm thanh thư giãn
    "Nghe mưa rơi YouTube",
    "Nghe tiếng sóng Google",
    "Nghe tiếng chim Google",
    "Nghe gió thổi YouTube",
    "Nghe tiếng chuông gió",
    "Nghe tiếng koto YouTube",
    "Nghe tiếng rừng YouTube",
    "Nghe tiếng suối YouTube",
    "Nghe tiếng gió chimes",
    "Nghe tiếng cá YouTube",
    "Nghe tiếng lò sưởi YouTube",
    "Nghe tiếng hồ nước YouTube",
    "Nghe tiếng lá xào xạc YouTube",
    "Nghe tiếng đồng cỏ YouTube",
    "Nghe tiếng mưa rừng YouTube",
    "Nghe tiếng thác nước YouTube",
    "Nghe tiếng chim hót YouTube",
    "Nghe tiếng sóng vỗ YouTube",
    "Nghe tiếng mưa trên mái nhà YouTube",
    "Nghe tiếng gió mùa thu YouTube",
    "Nghe tiếng chim trong rừng YouTube",
    "Nghe tiếng nước chảy nhẹ YouTube",
    "Nghe tiếng gió qua cánh đồng YouTube",
    "Nghe tiếng côn trùng ban đêm YouTube",
    "Nghe tiếng mưa rơi trên lá YouTube",
    "Nghe tiếng sóng biển đêm YouTube",
    "Nghe tiếng gió trên núi YouTube",
    "Nghe tiếng nước chảy trong suối YouTube",
    "Nghe tiếng chim hót buổi sáng YouTube",
    "Nghe tiếng lá rơi mùa thu YouTube",

    // Hoạt động sáng tạo và tổ chức
    "Dọn bàn học gọn",
    "Dọn góc phòng nhỏ",
    "Trang trí góc học",
    "Viết note cảm xúc",
    "Sắp xếp ảnh anime",
    "Tô màu trên app",
    "Tô màu mandala trên app",
    "Tô tranh số trên app",
    "Làm sổ tay bullet journal",
    "Viết thơ ngắn về anime",
    "Làm danh sách anime cần xem",
    "Trang trí khung ảnh anime",
    "Làm sticker dán anime",
    "Tạo playlist anime trên Spotify",
    "Viết review ngắn về anime",
    "Làm bảng tầm nhìn anime",
    "Tạo meme anime đơn giản",
    "Làm lịch anime handmade",
    "Viết truyện ngắn phong cách anime",
    "Làm bìa sách manga giả",
    "Tạo moodboard anime trên app",
    "Làm vòng tay phong cách anime",
    "Tạo bảng màu anime trên app",
    "Làm bookmark anime handmade",
    "Viết lời bài hát J-pop giả",
    "Làm bảng kế hoạch học anime",
    "Tạo bộ sưu tập fanart anime",
    "Làm hộp đựng đồ anime",
    "Tạo bảng sticker anime trên app",
    "Làm tranh ghép anime",
    "Tạo ảnh bìa Discord anime",
    "Làm khung ảnh cosplay",
    "Tạo bộ sưu tập quote anime",
    "Làm sổ tay ghi chú anime",
    "Tạo ảnh bìa Facebook anime",
    "Làm bảng kế hoạch cosplay",
    "Tạo bộ sưu tập hình nền anime",
    "Làm vòng cổ phong cách anime",
    "Tạo ảnh đại diện Discord anime",
    "Làm bảng kế hoạch xem anime",
    "Tạo bộ sưu tập OST anime",
    "Làm tranh vẽ tay anime",
    "Tạo ảnh bìa Spotify anime",
    "Làm bảng kế hoạch vẽ anime",
    "Tạo bộ sưu tập meme anime",
    "Làm vòng tay đan phong cách Nhật",
    "Tạo ảnh bìa YouTube anime",
    "Làm bảng kế hoạch học tiếng Nhật",
    "Tạo bộ sưu tập ảnh cosplay",
    "Làm tranh thêu phong cách anime",
    "Tạo ảnh bìa Steam anime",
    "Làm bảng kế hoạch chơi game anime",
    "Tạo bộ sưu tập ảnh văn hóa Nhật",
    "Làm tranh vẽ màu nước anime",
    "Tạo ảnh bìa Instagram anime",
    "Làm bảng kế hoạch nấu món Nhật",
    "Tạo bộ sưu tập ảnh lễ hội Nhật",
    "Làm tranh vẽ phấn phong cách anime",
    "Tạo ảnh bìa Pinterest anime",
    "Làm bảng kế hoạch học vẽ anime",
    "Tạo bộ sưu tập ảnh kimono",
    "Làm tranh vẽ bút chì anime",
    "Tạo ảnh bìa Twitter anime",
    "Làm bảng kế hoạch nghe nhạc anime",
    "Tạo bộ sưu tập ảnh hoa anh đào",
    "Làm tranh vẽ màu acrylic anime",
    "Tạo ảnh bìa TikTok anime",
    "Làm bảng kế hoạch cosplay anime",
    "Tạo bộ sưu tập ảnh núi Phú Sĩ",
    "Làm tranh vẽ màu dầu anime",
    "Tạo ảnh bìa Reddit anime",
    "Làm bảng kế hoạch học văn hóa Nhật",
    "Tạo bộ sưu tập ảnh đền chùa Nhật",
    "Làm tranh vẽ màu pastel anime",
    "Tạo ảnh bìa Tumblr anime",
    "Làm bảng kế hoạch xem phim Nhật",
    "Tạo bộ sưu tập ảnh phố cổ Nhật",
    "Làm tranh vẽ màu chì anime",
    "Tạo ảnh bìa LinkedIn anime",
    "Làm bảng kế hoạch học thư pháp Nhật",
    "Tạo bộ sưu tập ảnh đèn lồng Nhật",
    "Làm tranh vẽ màu gouache anime",
    "Tạo ảnh bìa WhatsApp anime",
    "Làm bảng kế hoạch học origami",
    "Tạo bộ sưu tập ảnh vườn Nhật",
    "Làm tranh vẽ màu marker anime",
    "Tạo ảnh bìa Snapchat anime",
    "Làm bảng kế hoạch học trà đạo",
    "Tạo bộ sưu tập ảnh món ăn Nhật",
    "Làm tranh vẽ màu than anime",
    "Tạo ảnh bìa Viber anime",
    "Làm bảng kế hoạch học J-pop",
    "Tạo bộ sưu tập ảnh nghệ thuật Nhật",
    "Làm tranh vẽ màu mực anime",
    "Tạo ảnh bìa Telegram anime",
    "Làm bảng kế hoạch học manga",
    "Tạo bộ sưu tập ảnh lễ hội hoa anh đào",
    "Làm tranh vẽ màu phấn dầu anime",
    "Tạo ảnh bìa WeChat anime",
    "Làm bảng kế hoạch học cosplay",
    "Tạo bộ sưu tập ảnh cảnh đêm Nhật",
    "Làm tranh vẽ màu bút bi anime",
    "Tạo ảnh bìa Line anime",
    "Làm bảng kế hoạch học tiếng Nhật cơ bản",
    "Tạo bộ sưu tập ảnh anime mùa thu",
    "Làm tranh vẽ màu highlighter anime",
    "Tạo ảnh bìa KakaoTalk anime",
    "Làm bảng kế hoạch học vẽ chibi",
    "Tạo bộ sưu tập ảnh anime mùa đông",
    "Làm tranh vẽ màu bút lông anime",
    "Tạo ảnh bìa Discord server anime",
    "Làm bảng kế hoạch học vẽ manga",
    "Tạo bộ sưu tập ảnh anime mùa xuân",
    "Làm tranh vẽ màu bút chấm anime",
    "Tạo ảnh bìa Steam profile anime",
    "Làm bảng kế hoạch học vẽ nhân vật anime",
    "Tạo bộ sưu tập ảnh anime mùa hè",
    "Làm tranh vẽ màu bút kỹ thuật anime",
    "Tạo ảnh bìa YouTube channel anime",
    "Làm bảng kế hoạch học vẽ cảnh anime",
    "Tạo bộ sưu tập ảnh anime lo-fi",
    "Làm tranh vẽ màu bút màu anime",
    "Tạo ảnh bìa Spotify playlist anime",
    "Làm bảng kế hoạch học vẽ phong cách Nhật",
    "Tạo bộ sưu tập ảnh anime pastel",
    "Làm tranh vẽ màu bút kim anime",
    "Tạo ảnh bìa Facebook profile anime",
    "Làm bảng kế hoạch học vẽ sticker anime",
    "Tạo bộ sưu tập ảnh anime kawaii",
    "Làm tranh vẽ màu bút mực anime",
    "Tạo ảnh bìa Instagram profile anime",
    "Làm bảng kế hoạch học vẽ biểu tượng anime",
    "Tạo bộ sưu tập ảnh anime chibi",
    "Làm tranh vẽ màu bút nước anime",
    "Tạo ảnh bìa Pinterest board anime",
    "Làm bảng kế hoạch học vẽ tranh lo-fi",
    "Tạo bộ sưu tập ảnh anime aesthetic",
    "Làm tranh vẽ màu bút màu nước anime",
    "Tạo ảnh bìa Twitter profile anime",
    "Làm bảng kế hoạch học vẽ tranh pastel",
    "Tạo bộ sưu tập ảnh anime retro",
    "Làm tranh vẽ màu bút màu dầu anime",
    "Tạo ảnh bìa Reddit profile anime",
    "Làm bảng kế hoạch học vẽ tranh kawaii",
    "Tạo bộ sưu tập ảnh anime vintage",
    "Làm tranh vẽ màu bút màu chì anime",
    "Tạo ảnh bìa Tumblr profile anime",
    "Làm bảng kế hoạch học vẽ tranh chibi",
    "Tạo bộ sưu tập ảnh anime minimalist",
    "Làm tranh vẽ màu bút màu neon anime",
    "Tạo ảnh bìa TikTok profile anime",
    "Làm bảng kế hoạch học vẽ tranh aesthetic",
    "Tạo bộ sưu tập ảnh anime studio Ghibli",
    "Làm tranh vẽ màu bút màu ánh kim anime",
    "Tạo ảnh bìa LinkedIn profile anime",
    "Làm bảng kế hoạch học vẽ tranh lo-fi Nhật",
    "Tạo bộ sưu tập ảnh anime phong cách Nhật",
    "Làm tranh vẽ màu bút màu metal anime",
    "Tạo ảnh bìa WhatsApp profile anime",
    "Làm bảng kế hoạch học vẽ tranh anime mùa thu",
    "Tạo bộ sưu tập ảnh anime mùa xuân Nhật",
    "Làm tranh vẽ màu bút màu pastel anime",
    "Tạo ảnh bìa Snapchat profile anime",
    "Làm bảng kế hoạch học vẽ tranh anime mùa đông",
    "Tạo bộ sưu tập ảnh anime mùa hè Nhật",
    "Làm tranh vẽ màu bút màu trong suốt anime",
    "Tạo ảnh bìa Viber profile anime",
    "Làm bảng kế hoạch học vẽ tranh anime mùa xuân",
    "Tạo bộ sưu tập ảnh anime mùa thu Nhật",
    "Làm tranh vẽ màu bút màu ánh nhũ anime",
    "Tạo ảnh bìa Telegram profile anime",
    "Làm bảng kế hoạch học vẽ tranh anime mùa hè",
    "Tạo bộ sưu tập ảnh anime mùa đông Nhật",
    "Làm tranh vẽ màu bút màu đa sắc anime",
    "Tạo ảnh bìa WeChat profile anime",
    "Làm bảng kế hoạch học vẽ tranh anime lo-fi",
    "Tạo bộ sưu tập ảnh anime pastel Nhật",
    "Làm tranh vẽ màu bút màu ombre anime",
    "Tạo ảnh bìa Line profile anime",
    "LUNCH!!!"
];

    // Cập nhật lời chào và chủ đề theo thời gian
    function updateGreetingAndTheme() {
        const hour = new Date().getHours();
        if (hour >= 5 && hour < 12) {
            greetingElement.textContent = "Chào buổi sáng!";
            body.classList.remove("bg-afternoon", "bg-evening");
            body.classList.add("bg-morning");
        } else if (hour >= 12 && hour < 18) {
            greetingElement.textContent = "Chào buổi chiều!";
            body.classList.remove("bg-morning", "bg-evening");
            body.classList.add("bg-afternoon");
        } else {
            greetingElement.textContent = "Chào buổi tối!";
            body.classList.remove("bg-morning", "bg-afternoon");
            body.classList.add("bg-evening");
        }
    }
    
    // Weather Fetching
    const weatherWidget = document.querySelector("#weatherWidget");
    const apiKey = "60b0126e9ffbc27a747b2c03af299d58"; // Replace with your API key
    const city = "Hanoi";
    const units = "metric";

    async function fetchWeather() {
        try {
            const response = await fetch(`https://api.openweathermap.org/data/2.5/weather?q=${city}&units=${units}&appid=${apiKey}&lang=vi`);
            const data = await response.json();

            const temp = Math.round(data.main.temp);
            const condition = data.weather[0].description;
            const iconCode = data.weather[0].icon;
            const iconUrl = `https://openweathermap.org/img/wn/${iconCode}@2x.png`;

            weatherWidget.innerHTML = `
                <img src="${iconUrl}" alt="${condition}" class="w-6 h-6">
                <span>${city}: ${temp}°C, ${condition}</span>
            `;
        } catch (error) {
            weatherWidget.innerHTML = `<span>Không lấy được thời tiết 😥</span>`;
            console.error("Weather fetch error:", error);
        }
    }

    fetchWeather();

    // Lấy gợi ý ngẫu nhiên
    async function getRandomSuggestion() {
        suggestBtn.disabled = true;
        loadingSpinner.classList.remove("hidden");
        suggestionElement.textContent = "";

        await new Promise(resolve => setTimeout(resolve, 1000)); // Giả lập loading

        const randomIndex = Math.floor(Math.random() * activities.length);
        const suggestion = activities[randomIndex];
        suggestionElement.textContent = suggestion;

        suggestBtn.disabled = false;
        loadingSpinner.classList.add("hidden");
    }

    // Chuyển đổi chế độ tối
    darkModeToggle.addEventListener("click", () => {
        document.documentElement.classList.toggle("dark");
        localStorage.setItem("darkMode", document.documentElement.classList.contains("dark"));
    });

    // Khôi phục chế độ tối
    if (localStorage.getItem("darkMode") === "true") {
        document.documentElement.classList.add("dark");
    }

    // Cập nhật khi tải trang
    updateGreetingAndTheme();
    
    // Xử lý sự kiện
    suggestBtn.addEventListener("click", getRandomSuggestion);
});